const genres = [
	{ name: "Action", id: 28 },
	{ category: "Adventure", id: 12 },
	{ category: "Animation", id: 16 },
	{ category: "Comedy", id: 35 },
	{ category: "Crime", id: 80 },
	{ category: "Documentary", id: 99 },
	{ category: "Drama", id: 18 },
	{ category: "Family", id: 10751 },
	{ category: "Fantasy", id: 14 },
	{ category: "History", id: 36 },
	{ category: "Horror", id: 27 },
	{ category: "Music", id: 10402 },
	{ category: "Mystery", id: 9648 },
	{ category: "Romance", id: 10749 },
	{ category: "Science Fiction", id: 878 },
	{ category: "TV Movie", id: 1077 },
	{ category: "Thriller", id: 53 },
	{ category: "War", id: 10752 },
	{ category: "Western", id: 37 },
];
